block_2011_02_04_10_29_18 = {
    'name' : '$name',
    'note' : '$note',
    'subjid' : '$subj',
    'date' : '$date',
    'time' : '$time',
    'host' : 'shs040',
    'variables' : {
        'freq' : '250',
    },
    # TODO: utils.get_expanded_vars_in_string accepts field delimiters (eg, ;), add text delimiters so fields can be wrapped (eg '')
    'user' : {
        'dur' : 500,
        'fs' : 44100,
        'isi' : 250,
        'postbuff' : 150,
        'prebuff' : 150,
    },
    'dynamic' : {
        'val_start' : 70,
        'intervals' : 2,
        'val_ceil_n' : 3,
        'val_floor' : 0,
        'val_floor_n' : 3,
        'val_ceil' : 80,
        'msg' : 'Cancelled by user',
        'steps' : [5, 5, 2, 2, 2, 2, 2, 2],
        'vals_to_avg' : 6,
        'track' : [0],
        'values_at_rev' : [],
        'downs' : 2,
        'units' : 'dB',
        'run_n_trials' : 0,
        'name' : 'level',
        'max_trials' : 60,
        'values' : [70],
        'good_run' : False,
        'mean' : nan,
        'ups' : 1,
        'sd' : nan,
    },
}
