# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pylabconfig.ui'
#
# Created: Mon Jul 12 22:20:24 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        Dialog.setMinimumSize(QtCore.QSize(100, 100))
        Dialog.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("shs_head16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.Experiment = QtGui.QGroupBox(Dialog)
        self.Experiment.setGeometry(QtCore.QRect(0, 0, 266, 551))
        self.Experiment.setTitle("")
        self.Experiment.setObjectName("Experiment")
        self.label_6 = QtGui.QLabel(self.Experiment)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setObjectName("label_6")
        self.RecordData = QtGui.QCheckBox(self.Experiment)
        self.RecordData.setGeometry(QtCore.QRect(10, 250, 103, 23))
        self.RecordData.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.RecordData.setIconSize(QtCore.QSize(16, 16))
        self.RecordData.setObjectName("RecordData")
        self.InputMethod = QtGui.QComboBox(self.Experiment)
        self.InputMethod.setGeometry(QtCore.QRect(155, 360, 101, 25))
        self.InputMethod.setObjectName("InputMethod")
        self.InputMethod.addItem("")
        self.InputMethod.addItem("")
        self.InputChars = QtGui.QLineEdit(self.Experiment)
        self.InputChars.setGeometry(QtCore.QRect(10, 390, 246, 26))
        self.InputChars.setObjectName("InputChars")
        self.label_16 = QtGui.QLabel(self.Experiment)
        self.label_16.setGeometry(QtCore.QRect(155, 190, 101, 20))
        self.label_16.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_16.setObjectName("label_16")
        self.Name = QtGui.QLineEdit(self.Experiment)
        self.Name.setGeometry(QtCore.QRect(10, 70, 116, 25))
        self.Name.setObjectName("Name")
        self.DataPath = QtGui.QLineEdit(self.Experiment)
        self.DataPath.setGeometry(QtCore.QRect(10, 310, 226, 26))
        self.DataPath.setObjectName("DataPath")
        self.DataPath_Get = QtGui.QPushButton(self.Experiment)
        self.DataPath_Get.setGeometry(QtCore.QRect(235, 310, 21, 26))
        self.DataPath_Get.setObjectName("DataPath_Get")
        self.TrialsPerBlock = QtGui.QSpinBox(self.Experiment)
        self.TrialsPerBlock.setGeometry(QtCore.QRect(200, 210, 58, 26))
        self.TrialsPerBlock.setFrame(True)
        self.TrialsPerBlock.setProperty("value", 10)
        self.TrialsPerBlock.setObjectName("TrialsPerBlock")
        self.Comments = QtGui.QPlainTextEdit(self.Experiment)
        self.Comments.setGeometry(QtCore.QRect(10, 120, 246, 61))
        self.Comments.setObjectName("Comments")
        self.label_7 = QtGui.QLabel(self.Experiment)
        self.label_7.setGeometry(QtCore.QRect(10, 290, 121, 20))
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setObjectName("label_7")
        self.label_15 = QtGui.QLabel(self.Experiment)
        self.label_15.setGeometry(QtCore.QRect(10, 100, 121, 20))
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setObjectName("label_15")
        self.label_17 = QtGui.QLabel(self.Experiment)
        self.label_17.setGeometry(QtCore.QRect(145, 50, 101, 20))
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtGui.QLabel(self.Experiment)
        self.label_18.setGeometry(QtCore.QRect(10, 360, 91, 20))
        self.label_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_18.setObjectName("label_18")
        self.label_5 = QtGui.QLabel(self.Experiment)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 101, 20))
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setObjectName("label_5")
        self.ExperimentalMethod = QtGui.QComboBox(self.Experiment)
        self.ExperimentalMethod.setGeometry(QtCore.QRect(140, 70, 116, 25))
        self.ExperimentalMethod.setObjectName("ExperimentalMethod")
        self.ExperimentalMethod.addItem("")
        self.ExperimentalMethod.addItem("")
        self.label_26 = QtGui.QLabel(self.Experiment)
        self.label_26.setGeometry(QtCore.QRect(10, 190, 51, 20))
        self.label_26.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_26.setObjectName("label_26")
        self.Subject = QtGui.QLineEdit(self.Experiment)
        self.Subject.setGeometry(QtCore.QRect(10, 210, 81, 25))
        self.Subject.setObjectName("Subject")
        self.label_28 = QtGui.QLabel(self.Experiment)
        self.label_28.setGeometry(QtCore.QRect(10, 28, 241, 10))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_28.setFont(font)
        self.label_28.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_28.setFrameShape(QtGui.QFrame.HLine)
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.StimulusSets = QtGui.QGroupBox(Dialog)
        self.StimulusSets.setGeometry(QtCore.QRect(267, 0, 266, 551))
        self.StimulusSets.setTitle("")
        self.StimulusSets.setObjectName("StimulusSets")
        self.Stimulus_Names = QtGui.QListWidget(self.StimulusSets)
        self.Stimulus_Names.setGeometry(QtCore.QRect(10, 70, 116, 101))
        self.Stimulus_Names.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.Stimulus_Names.setObjectName("Stimulus_Names")
        self.Stimulus_Type = QtGui.QComboBox(self.StimulusSets)
        self.Stimulus_Type.setGeometry(QtCore.QRect(140, 70, 116, 25))
        self.Stimulus_Type.setObjectName("Stimulus_Type")
        self.Stimulus_Type.addItem("")
        self.Stimulus_Type.addItem("")
        self.label_19 = QtGui.QLabel(self.StimulusSets)
        self.label_19.setGeometry(QtCore.QRect(140, 50, 101, 20))
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setObjectName("label_19")
        self.label_8 = QtGui.QLabel(self.StimulusSets)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setObjectName("label_8")
        self.Stimulus_Order = QtGui.QLineEdit(self.StimulusSets)
        self.Stimulus_Order.setGeometry(QtCore.QRect(10, 320, 246, 26))
        self.Stimulus_Order.setObjectName("Stimulus_Order")
        self.Stimulus_FileMask = QtGui.QLineEdit(self.StimulusSets)
        self.Stimulus_FileMask.setGeometry(QtCore.QRect(10, 380, 246, 26))
        self.Stimulus_FileMask.setObjectName("Stimulus_FileMask")
        self.label_24 = QtGui.QLabel(self.StimulusSets)
        self.label_24.setGeometry(QtCore.QRect(10, 300, 181, 20))
        self.label_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_24.setObjectName("label_24")
        self.Stimulus_PathToFiles = QtGui.QLineEdit(self.StimulusSets)
        self.Stimulus_PathToFiles.setGeometry(QtCore.QRect(10, 200, 246, 26))
        self.Stimulus_PathToFiles.setObjectName("Stimulus_PathToFiles")
        self.label_21 = QtGui.QLabel(self.StimulusSets)
        self.label_21.setGeometry(QtCore.QRect(10, 180, 51, 20))
        self.label_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtGui.QLabel(self.StimulusSets)
        self.label_22.setGeometry(QtCore.QRect(10, 240, 51, 20))
        self.label_22.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_22.setObjectName("label_22")
        self.Stimulus_Repeat = QtGui.QCheckBox(self.StimulusSets)
        self.Stimulus_Repeat.setGeometry(QtCore.QRect(10, 420, 71, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Stimulus_Repeat.sizePolicy().hasHeightForWidth())
        self.Stimulus_Repeat.setSizePolicy(sizePolicy)
        self.Stimulus_Repeat.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Stimulus_Repeat.setObjectName("Stimulus_Repeat")
        self.Stimulus_PathToText = QtGui.QLineEdit(self.StimulusSets)
        self.Stimulus_PathToText.setGeometry(QtCore.QRect(10, 260, 246, 26))
        self.Stimulus_PathToText.setObjectName("Stimulus_PathToText")
        self.label_25 = QtGui.QLabel(self.StimulusSets)
        self.label_25.setGeometry(QtCore.QRect(10, 360, 181, 20))
        self.label_25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_25.setObjectName("label_25")
        self.label_20 = QtGui.QLabel(self.StimulusSets)
        self.label_20.setGeometry(QtCore.QRect(140, 100, 101, 20))
        self.label_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_20.setObjectName("label_20")
        self.Stimulus_Load = QtGui.QComboBox(self.StimulusSets)
        self.Stimulus_Load.setGeometry(QtCore.QRect(140, 120, 116, 25))
        self.Stimulus_Load.setObjectName("Stimulus_Load")
        self.Stimulus_Load.addItem("")
        self.Stimulus_Load.addItem("")
        self.label_10 = QtGui.QLabel(self.StimulusSets)
        self.label_10.setGeometry(QtCore.QRect(10, 50, 101, 20))
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setObjectName("label_10")
        self.label_29 = QtGui.QLabel(self.StimulusSets)
        self.label_29.setGeometry(QtCore.QRect(10, 28, 241, 10))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_29.setFont(font)
        self.label_29.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_29.setFrameShape(QtGui.QFrame.HLine)
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.SettingsFile = QtGui.QGroupBox(Dialog)
        self.SettingsFile.setEnabled(True)
        self.SettingsFile.setGeometry(QtCore.QRect(0, 550, 801, 51))
        self.SettingsFile.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SettingsFile.setTitle("")
        self.SettingsFile.setFlat(True)
        self.SettingsFile.setObjectName("SettingsFile")
        self.Run = QtGui.QPushButton(self.SettingsFile)
        self.Run.setGeometry(QtCore.QRect(730, 20, 61, 25))
        self.Run.setObjectName("Run")
        self.settingsSave = QtGui.QPushButton(self.SettingsFile)
        self.settingsSave.setGeometry(QtCore.QRect(580, 20, 51, 25))
        self.settingsSave.setObjectName("settingsSave")
        self.settingsLoad = QtGui.QPushButton(self.SettingsFile)
        self.settingsLoad.setGeometry(QtCore.QRect(530, 20, 51, 25))
        self.settingsLoad.setObjectName("settingsLoad")
        self.settingsFilePath = QtGui.QLineEdit(self.SettingsFile)
        self.settingsFilePath.setGeometry(QtCore.QRect(131, 20, 401, 26))
        self.settingsFilePath.setObjectName("settingsFilePath")
        self.label = QtGui.QLabel(self.SettingsFile)
        self.label.setGeometry(QtCore.QRect(10, 25, 121, 16))
        self.label.setObjectName("label")
        self.Cancel = QtGui.QPushButton(self.SettingsFile)
        self.Cancel.setGeometry(QtCore.QRect(670, 20, 61, 25))
        self.Cancel.setObjectName("Cancel")
        self.label_31 = QtGui.QLabel(self.SettingsFile)
        self.label_31.setGeometry(QtCore.QRect(10, 6, 781, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_31.setFont(font)
        self.label_31.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_31.setFrameShape(QtGui.QFrame.HLine)
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.Variables = QtGui.QGroupBox(Dialog)
        self.Variables.setGeometry(QtCore.QRect(535, 0, 266, 551))
        self.Variables.setTitle("")
        self.Variables.setObjectName("Variables")
        self.FactorialVars = QtGui.QListWidget(self.Variables)
        self.FactorialVars.setGeometry(QtCore.QRect(10, 70, 116, 101))
        self.FactorialVars.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.FactorialVars.setObjectName("FactorialVars")
        self.VariableType = QtGui.QComboBox(self.Variables)
        self.VariableType.setGeometry(QtCore.QRect(140, 70, 116, 25))
        self.VariableType.setObjectName("VariableType")
        self.VariableType.addItem("")
        self.VariableType.addItem("")
        self.VariableType.addItem("")
        self.label_23 = QtGui.QLabel(self.Variables)
        self.label_23.setGeometry(QtCore.QRect(140, 50, 101, 20))
        self.label_23.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_23.setObjectName("label_23")
        self.label_9 = QtGui.QLabel(self.Variables)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setObjectName("label_9")
        self.label_11 = QtGui.QLabel(self.Variables)
        self.label_11.setGeometry(QtCore.QRect(10, 50, 101, 20))
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setObjectName("label_11")
        self.OtherLevels = QtGui.QListView(self.Variables)
        self.OtherLevels.setGeometry(QtCore.QRect(140, 200, 116, 101))
        self.OtherLevels.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.OtherLevels.setObjectName("OtherLevels")
        self.label_12 = QtGui.QLabel(self.Variables)
        self.label_12.setGeometry(QtCore.QRect(10, 180, 101, 20))
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setObjectName("label_12")
        self.OtherVars = QtGui.QListView(self.Variables)
        self.OtherVars.setGeometry(QtCore.QRect(10, 200, 116, 101))
        self.OtherVars.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.OtherVars.setObjectName("OtherVars")
        self.label_27 = QtGui.QLabel(self.Variables)
        self.label_27.setGeometry(QtCore.QRect(140, 180, 101, 20))
        self.label_27.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_27.setObjectName("label_27")
        self.listWidget = QtGui.QListWidget(self.Variables)
        self.listWidget.setGeometry(QtCore.QRect(10, 440, 246, 81))
        self.listWidget.setObjectName("listWidget")
        self.label_13 = QtGui.QLabel(self.Variables)
        self.label_13.setGeometry(QtCore.QRect(10, 420, 101, 20))
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtGui.QLabel(self.Variables)
        self.label_14.setGeometry(QtCore.QRect(10, 310, 101, 20))
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setObjectName("label_14")
        self.listWidget_2 = QtGui.QListWidget(self.Variables)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 330, 246, 81))
        self.listWidget_2.setObjectName("listWidget_2")
        self.label_30 = QtGui.QLabel(self.Variables)
        self.label_30.setGeometry(QtCore.QRect(10, 28, 241, 10))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_30.setFont(font)
        self.label_30.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_30.setFrameShape(QtGui.QFrame.HLine)
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Pylab - Configure Experiment", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Experiment", None, QtGui.QApplication.UnicodeUTF8))
        self.RecordData.setText(QtGui.QApplication.translate("Dialog", "Record Data", None, QtGui.QApplication.UnicodeUTF8))
        self.InputMethod.setItemText(0, QtGui.QApplication.translate("Dialog", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.InputMethod.setItemText(1, QtGui.QApplication.translate("Dialog", "Key", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "Trials Per Block", None, QtGui.QApplication.UnicodeUTF8))
        self.DataPath_Get.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Data Path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "Method", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Input Method", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.ExperimentalMethod.setItemText(0, QtGui.QApplication.translate("Dialog", "Constant", None, QtGui.QApplication.UnicodeUTF8))
        self.ExperimentalMethod.setItemText(1, QtGui.QApplication.translate("Dialog", "Adaptive", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Dialog", "Subject", None, QtGui.QApplication.UnicodeUTF8))
        self.Stimulus_Type.setItemText(0, QtGui.QApplication.translate("Dialog", "SoundFiles", None, QtGui.QApplication.UnicodeUTF8))
        self.Stimulus_Type.setItemText(1, QtGui.QApplication.translate("Dialog", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Stimulus Sets", None, QtGui.QApplication.UnicodeUTF8))
        self.Stimulus_Order.setToolTip(QtGui.QApplication.translate("Dialog", "0 = random; 1 = natural order; [array] to specify (default = 1)", None, QtGui.QApplication.UnicodeUTF8))
        self.Stimulus_FileMask.setToolTip(QtGui.QApplication.translate("Dialog", "0 = random; 1 = natural order; [array] to specify (default = 1)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Dialog", "Order", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Dialog", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Dialog", "Text File", None, QtGui.QApplication.UnicodeUTF8))
        self.Stimulus_Repeat.setText(QtGui.QApplication.translate("Dialog", "Repeat", None, QtGui.QApplication.UnicodeUTF8))
        self.Stimulus_PathToText.setToolTip(QtGui.QApplication.translate("Dialog", "The full path to a text file with the corresponding text. The format of the file should be one space-delimited line per token in the format: \'CUNY001 4 They LOOKED UP at the BLUE SKY.\' where CUNY001 is the filename (no extension), 4 is the number of keywords, and the rest of the line is the text.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Dialog", "File Mask", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.Stimulus_Load.setItemText(0, QtGui.QApplication.translate("Dialog", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.Stimulus_Load.setItemText(1, QtGui.QApplication.translate("Dialog", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.Run.setText(QtGui.QApplication.translate("Dialog", "Run!", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsSave.setText(QtGui.QApplication.translate("Dialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsLoad.setText(QtGui.QApplication.translate("Dialog", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Settings File name:", None, QtGui.QApplication.UnicodeUTF8))
        self.Cancel.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.VariableType.setItemText(0, QtGui.QApplication.translate("Dialog", "Stim", None, QtGui.QApplication.UnicodeUTF8))
        self.VariableType.setItemText(1, QtGui.QApplication.translate("Dialog", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.VariableType.setItemText(2, QtGui.QApplication.translate("Dialog", "Dynamic", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Dialog", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Variables", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Factorial Levels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Dialog", "Other Levels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "User Vars", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Dynamic", None, QtGui.QApplication.UnicodeUTF8))

