# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'subject_manager.ui'
#
# Created: Mon Feb 22 12:48:55 2010
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(562, 369)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 541, 311))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 61, 16))
        self.label_6.setObjectName("label_6")
        self.birthdate_dateEdit = QtGui.QDateEdit(self.tab)
        self.birthdate_dateEdit.setGeometry(QtCore.QRect(90, 130, 151, 21))
        self.birthdate_dateEdit.setObjectName("birthdate_dateEdit")
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(300, 10, 61, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(300, 40, 61, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(300, 70, 61, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(300, 100, 71, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(300, 130, 81, 16))
        self.label_11.setObjectName("label_11")
        self.contact_add_checkBox = QtGui.QCheckBox(self.tab)
        self.contact_add_checkBox.setGeometry(QtCore.QRect(300, 160, 221, 20))
        self.contact_add_checkBox.setObjectName("contact_add_checkBox")
        self.audiogram_dateEdit = QtGui.QDateEdit(self.tab)
        self.audiogram_dateEdit.setGeometry(QtCore.QRect(380, 130, 151, 21))
        self.audiogram_dateEdit.setObjectName("audiogram_dateEdit")
        self.consent_dateEdit = QtGui.QDateEdit(self.tab)
        self.consent_dateEdit.setGeometry(QtCore.QRect(380, 100, 151, 21))
        self.consent_dateEdit.setObjectName("consent_dateEdit")
        self.first_name_lineEdit = QtGui.QLineEdit(self.tab)
        self.first_name_lineEdit.setGeometry(QtCore.QRect(90, 10, 181, 21))
        self.first_name_lineEdit.setObjectName("first_name_lineEdit")
        self.last_name_lineEdit = QtGui.QLineEdit(self.tab)
        self.last_name_lineEdit.setGeometry(QtCore.QRect(90, 40, 181, 21))
        self.last_name_lineEdit.setObjectName("last_name_lineEdit")
        self.email_lineEdit = QtGui.QLineEdit(self.tab)
        self.email_lineEdit.setGeometry(QtCore.QRect(90, 70, 181, 21))
        self.email_lineEdit.setObjectName("email_lineEdit")
        self.phone_lineEdit = QtGui.QLineEdit(self.tab)
        self.phone_lineEdit.setGeometry(QtCore.QRect(90, 100, 181, 21))
        self.phone_lineEdit.setObjectName("phone_lineEdit")
        self.subject_lineEdit = QtGui.QLineEdit(self.tab)
        self.subject_lineEdit.setGeometry(QtCore.QRect(90, 160, 131, 21))
        self.subject_lineEdit.setObjectName("subject_lineEdit")
        self.ethnic_id_comboBox = QtGui.QComboBox(self.tab)
        self.ethnic_id_comboBox.setGeometry(QtCore.QRect(380, 10, 151, 21))
        self.ethnic_id_comboBox.setObjectName("ethnic_id_comboBox")
        self.race_comboBox = QtGui.QComboBox(self.tab)
        self.race_comboBox.setGeometry(QtCore.QRect(380, 40, 151, 21))
        self.race_comboBox.setObjectName("race_comboBox")
        self.gender_comboBox = QtGui.QComboBox(self.tab)
        self.gender_comboBox.setGeometry(QtCore.QRect(380, 70, 151, 21))
        self.gender_comboBox.setObjectName("gender_comboBox")
        self.add_pushButton = QtGui.QPushButton(self.tab)
        self.add_pushButton.setGeometry(QtCore.QRect(442, 250, 81, 32))
        self.add_pushButton.setObjectName("add_pushButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.uid_comboBox = QtGui.QComboBox(self.tab_2)
        self.uid_comboBox.setGeometry(QtCore.QRect(10, 10, 121, 26))
        self.uid_comboBox.setObjectName("uid_comboBox")
        self.ieee_lineEdit = QtGui.QLineEdit(self.tab_2)
        self.ieee_lineEdit.setGeometry(QtCore.QRect(70, 60, 161, 22))
        self.ieee_lineEdit.setObjectName("ieee_lineEdit")
        self.cuny_lineEdit = QtGui.QLineEdit(self.tab_2)
        self.cuny_lineEdit.setGeometry(QtCore.QRect(70, 90, 161, 22))
        self.cuny_lineEdit.setObjectName("cuny_lineEdit")
        self.hint_lineEdit = QtGui.QLineEdit(self.tab_2)
        self.hint_lineEdit.setGeometry(QtCore.QRect(70, 120, 161, 22))
        self.hint_lineEdit.setObjectName("hint_lineEdit")
        self.notes_lineEdit = QtGui.QLineEdit(self.tab_2)
        self.notes_lineEdit.setGeometry(QtCore.QRect(310, 60, 221, 51))
        self.notes_lineEdit.setObjectName("notes_lineEdit")
        self.cid_lineEdit = QtGui.QLineEdit(self.tab_2)
        self.cid_lineEdit.setGeometry(QtCore.QRect(70, 150, 161, 22))
        self.cid_lineEdit.setObjectName("cid_lineEdit")
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(10, 150, 61, 16))
        self.label_14.setObjectName("label_14")
        self.name_label = QtGui.QLabel(self.tab_2)
        self.name_label.setGeometry(QtCore.QRect(150, 20, 241, 16))
        self.name_label.setObjectName("name_label")
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(10, 60, 61, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(10, 90, 61, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(10, 120, 61, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtGui.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(260, 60, 61, 16))
        self.label_19.setObjectName("label_19")
        self.contact_edit_checkBox = QtGui.QCheckBox(self.tab_2)
        self.contact_edit_checkBox.setGeometry(QtCore.QRect(260, 120, 221, 20))
        self.contact_edit_checkBox.setObjectName("contact_edit_checkBox")
        self.edit_save_pushButton = QtGui.QPushButton(self.tab_2)
        self.edit_save_pushButton.setGeometry(QtCore.QRect(442, 250, 81, 32))
        self.edit_save_pushButton.setObjectName("edit_save_pushButton")
        self.tabWidget.addTab(self.tab_2, "")
        self.close_pushButton = QtGui.QPushButton(Form)
        self.close_pushButton.setGeometry(QtCore.QRect(450, 330, 91, 32))
        self.close_pushButton.setObjectName("close_pushButton")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.close_pushButton, QtCore.SIGNAL("clicked()"), Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "First Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Last Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Email", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Phone #", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Birthdate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Subject #", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Ethnic ID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Race", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Gender", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Consent", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Audiogram", None, QtGui.QApplication.UnicodeUTF8))
        self.contact_add_checkBox.setText(QtGui.QApplication.translate("Form", "Consent to contact?", None, QtGui.QApplication.UnicodeUTF8))
        self.add_pushButton.setText(QtGui.QApplication.translate("Form", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Form", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "CID", None, QtGui.QApplication.UnicodeUTF8))
        self.name_label.setText(QtGui.QApplication.translate("Form", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Form", "IEEE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Form", "CUNY", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "HINT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Form", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.contact_edit_checkBox.setText(QtGui.QApplication.translate("Form", "Consent to contact?", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_save_pushButton.setText(QtGui.QApplication.translate("Form", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.close_pushButton.setText(QtGui.QApplication.translate("Form", "Close", None, QtGui.QApplication.UnicodeUTF8))

